eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#hystrix-feign-1  开启feign 的断路器
feign:
  hystrix:
    enabled: true