

#http请求地址和资源文件映射如下:
#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#      springcloudConfigs 此处为独立到项目，目前只有一个文件夹，里面放置了配置文件
#  http://localhost:8888/foo/dev  意思为 foo属性到dev环境的值
        git:
          uri: https://github.com/zzyua/springcloudConfigs
          search-paths: respo
          default-label: master
          username: 260787342@qq.com
          password: zhenyu7.16

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/